# Generated by Django 6.1 on 2026-09-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alumni_password_alumni_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='password',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='username',
        ),
    ]
