# Generated by Django 6.1 on 2026-09-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_alumni_password_remove_alumni_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='company',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='alumni',
            name='position',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
