# Generated by Django 6.1 on 2026-09-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alumni_company_alumni_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='kmeans_cluster',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='knn_most_similar_alumni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='recommended_alumni_top5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='sentiment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='batch',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
