# Generated by Django 6.1 on 2026-09-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alumni_feedback_alumni_kmeans_cluster_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='recommended_alumni_top5',
            new_name='knn_similar_alumni',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='knn_most_similar_alumni',
        ),
        migrations.AddField(
            model_name='alumni',
            name='recommended_alumni',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='batch',
            field=models.IntegerField(default=2027),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
