# Generated by Django 6.1 on 2026-09-22 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alumni_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_name', models.CharField(choices=[('kmeans', 'KMeans'), ('knn', 'KNN'), ('recommendation', 'Recommendation'), ('sentiment', 'Sentiment')], default='kmeans', max_length=30)),
                ('cluster', models.IntegerField(blank=True, null=True)),
                ('similar_alumni', models.TextField(blank=True, default='')),
                ('recommended_alumni', models.TextField(blank=True, default='')),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('sentiment', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='algorithm_results', to='accounts.alumni')),
            ],
            options={
                'verbose_name': 'Algorithm Result',
                'verbose_name_plural': 'Algorithm Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
