# Generated by Django 6.1 on 2026-09-22 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('networking', 'Networking'), ('career', 'Career & Learning'), ('reunion', 'Reunion'), ('community', 'Community'), ('webinar', 'Webinar')], default='community', max_length=20)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_online', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=220)),
                ('meeting_link', models.URLField(blank=True)),
                ('capacity', models.PositiveIntegerField(default=100)),
                ('chief_guest', models.CharField(blank=True, max_length=140)),
                ('chief_guest_title', models.CharField(blank=True, max_length=180)),
                ('chief_guest_bio', models.TextField(blank=True)),
                ('featured_alumni', models.CharField(blank=True, max_length=140)),
                ('featured_alumni_role', models.CharField(blank=True, max_length=180)),
                ('agenda', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['event_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('register_number', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('attendance', models.CharField(max_length=20)),
                ('guests', models.PositiveIntegerField(default=0)),
                ('food_preference', models.CharField(blank=True, max_length=30)),
                ('special_requirements', models.CharField(blank=True, max_length=300)),
                ('lunch_required', models.CharField(default='No', max_length=10)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='accounts.event')),
            ],
            options={
                'ordering': ['-registered_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'register_number'), name='unique_event_registration')],
            },
        ),
    ]
