# Generated by Django 6.1 on 2026-09-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_event_eventregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('IT', 'IT & Software'), ('DATA', 'Data & Analytics'), ('AI', 'AI & Machine Learning'), ('WEB', 'Web Development'), ('CLOUD', 'Cloud & DevOps'), ('INTERNSHIP', 'Internship'), ('OTHER', 'Other')], default='IT', max_length=30)),
                ('experience', models.CharField(choices=[('Fresher', 'Fresher'), ('0-1 Years', '0-1 Years'), ('1-2 Years', '1-2 Years'), ('2-3 Years', '2-3 Years'), ('3+ Years', '3+ Years')], default='Fresher', max_length=50)),
                ('description', models.TextField()),
                ('skills', models.CharField(blank=True, max_length=500, null=True)),
                ('job_type', models.CharField(default='Full Time', max_length=50)),
                ('company_website', models.URLField(blank=True, null=True)),
                ('apply_url', models.URLField()),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
